// Generated by CoffeeScript 1.3.3

jQuery(function($) {
  var updateValue;
  updateValue = function($control) {
    var added, i;
    added = (function() {
      var _i, _len, _ref, _results;
      _ref = $('li.added', $control);
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        _results.push($(i).attr('data-id'));
      }
      return _results;
    })();
    return $('input', $control).val(JSON.stringify(added));
  };
  $('.tree-select li > .item > .add').on('click', function() {
    var $added, $control, $item;
    $item = $(this).closest('li');
    $control = $(this).closest('.tree-select');
    if ($item.hasClass('added')) {
      return false;
    }
    $item.addClass('added');
    $added = $('<li />');
    $added.html($item.attr('data-aloneName'));
    $added.prepend($('<span class="remove">odebrat</span>'));
    $added.data('treeItem', $item);
    $('ul.added', $control).append($added);
    updateValue($control);
    return false;
  });
  $('.tree-select li > .item').on('click', function() {
    return $(this).closest('li').toggleClass('opened');
  });
  $(document).on('click', '.tree-select .remove', function() {
    var $control, $item;
    $item = $(this).closest('li');
    $control = $(this).closest('.tree-select');
    $item.data('treeItem').removeClass('added');
    $item.remove();
    updateValue($control);
    return false;
  });
  return $('.tree-select li.added').each(function() {
    $(this).removeClass('added');
    return $('> .item > .add', this).trigger('click');
  });
});
